// <auto-generated />
using Infraestructura.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructura.Data.Migrations
{
    [DbContext(typeof(DbfirstContext))]
    partial class DbfirstContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("Core.Entities.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<int>("Age")
                        .HasMaxLength(45)
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Name" }, "name")
                        .IsUnique();

                    b.ToTable("driver", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Name" }, "name")
                        .IsUnique()
                        .HasDatabaseName("name1");

                    b.ToTable("team", (string)null);
                });

            modelBuilder.Entity("TeamDriver", b =>
                {
                    b.Property<int>("IdTeam")
                        .HasColumnType("int(11)")
                        .HasColumnName("idTeam");

                    b.Property<int>("IdDriver")
                        .HasColumnType("int(11)")
                        .HasColumnName("idDriver");

                    b.HasKey("IdTeam", "IdDriver")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "IdDriver" }, "idDriver");

                    b.ToTable("teamDriver", (string)null);
                });

            modelBuilder.Entity("TeamDriver", b =>
                {
                    b.HasOne("Core.Entities.Driver", null)
                        .WithMany()
                        .HasForeignKey("IdDriver")
                        .IsRequired()
                        .HasConstraintName("teamDriver_ibfk_1");

                    b.HasOne("Core.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("IdTeam")
                        .IsRequired()
                        .HasConstraintName("teamDriver_ibfk_2");
                });
#pragma warning restore 612, 618
        }
    }
}
